name = "recursion_example"

[env]
HOP = "first_hop"

[first_hop.vars]
var.path = [".", ".second_hop.vars"]

[second_hop.vars]
var = "second_hop_value"

[recursive.vars]
var.path = [".", "${HOP}"]
var.type = "gear"

[recursive2.vars]
var1.path = ["3.secrets.cog.toml", "sops"]
var1.type = "gear"
